Repository govuk-one-login/performance-testing, pull requests merged in 2023-10, with the labels that each got.

#344 [QA-342] Add BTM SQS permissions
  deploy/template.yaml
Labels: cloudformation

#347 [QA-345] Bump `eslint-plugin` and `eslint-config-standard-with-typescript` packages
  deploy/scripts/package-lock.json
  deploy/scripts/package.json
  deploy/scripts/src/common/utils/jslib/aws-sqs.d.ts
Labels: dependencies, javascript

#352 [QA-347]: Add low volume profile for SPOT
  deploy/scripts/src/spot/test.ts
Labels: k6

#351 [QA-346] Use xk6 extension for statsd output
  deploy/Dockerfile
  deploy/template.yaml
Labels: docker, opentelemetry, cloudformation

#353 [QA-350] Update CODEOWNERS with new organisation team
  .github/CODEOWNERS
Labels: documentation

#358 [QA-351] Update references from `alphagov/di-devplatform-performance` to `govuk-one-login/performance-testing`
  .github/CODEOWNERS
  .github/workflows/feature-branch-publish.yaml
  README.md
  deploy/README.md
  deploy/scripts/package.json
  deploy/template.yaml
Labels: documentation, github_actions, cloudformation

#361 [QA-268]: Added custom metric to track iterations
  deploy/scripts/src/common/unit-tests.ts
  deploy/scripts/src/common/utils/custom_metric/counter.ts
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#368 [QA-358] Update `devplatform-upload` action location
  .github/workflows/publish.yaml
Labels: github_actions

#371 Added changes to track iteration count in all scripts
  deploy/scripts/src/accounts/id-reuse.ts
  deploy/scripts/src/accounts/test.ts
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/btm/test.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/scripts/src/cri-kiwi/ipvr.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/kbv.ts
  deploy/scripts/src/spot/test.ts
  deploy/scripts/src/txma/test.ts
Labels: k6
