Repository govuk-one-login/performance-testing, pull requests merged in 2023-08, with the labels that each got.

#245 DCMAW-5597: Added load profile
  deploy/scripts/src/mobile/authorize.test.ts
Labels: k6

#248 [QA-287]: Fix Audience ID and Client ID
  deploy/scripts/src/spot/requestGenerator/spotReqGen.ts
Labels: k6

#252 DCMAW-5598: Add load profile for the frontend E2E journey
  deploy/scripts/src/mobile/frontend-e2e.test.ts
Labels: k6

#249 [QA-288]: Update VC data in SPOT request
  deploy/scripts/src/spot/requestGenerator/spotReqGen.ts
Labels: k6

#253 [QA-292] Use `submitForm()` in Authentication script
  deploy/scripts/src/authentication/test.ts
  deploy/template.yaml
Labels: k6, cloudformation

#254 [QA-293] Use `submitForm()` in IPV Core script
  deploy/scripts/src/ipv-core/data/addressStub.json
  deploy/scripts/src/ipv-core/data/drivingLicence.json
  deploy/scripts/src/ipv-core/data/drivingLicenceStub.json
  deploy/scripts/src/ipv-core/data/fraudStub.json
  deploy/scripts/src/ipv-core/data/kbvData.json
  deploy/scripts/src/ipv-core/data/passport.json
  deploy/scripts/src/ipv-core/data/passportStub.json
  deploy/scripts/src/ipv-core/data/stubUser.json
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#255 [QA-288]: Updated JWT Tokens for SPOT request
  deploy/scripts/src/spot/requestGenerator/spotReqGen.ts
Labels: k6

#256 [QA-290]: Updated account management scripts
  deploy/scripts/src/accounts/test.ts
Labels: k6

#257 [QA-296] Use `submitForm()` in CRI Lime script
  deploy/scripts/src/cri-lime/data/drivingLicenceDVAData.csv
  deploy/scripts/src/cri-lime/data/drivingLicenceDVLAData.csv
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#265 [QA-302]: Added tags to account management script
  deploy/scripts/src/accounts/test.ts
Labels: k6

#264 [QA-301] Limit static resources to `.account.gov.uk`
  deploy/scripts/src/common/utils/request/static.ts
Labels: k6

#272 [QA-304]: Updated load profile of Account Management script
  deploy/scripts/src/accounts/test.ts
Labels: k6

#273 [QA-295] Use `submitForm()` in CRI Orange scripts
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/kbv.ts
Labels: k6

#233 [QA-282] : Added IPVR scripts
  deploy/scripts/src/common/utils/jslib/index.d.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/scripts/src/cri-kiwi/ipvr.ts
  deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqFormat.ts
  deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqGen.ts
  deploy/template.yaml
Labels: k6, cloudformation

#266 [QA-298] Use `submitForm()` in CRI Kiwi script
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/template.yaml
Labels: k6, cloudformation

#278 [QA-308]: Added tags to groups and requests of Auth scenarios
  deploy/scripts/src/authentication/test.ts
Labels: k6

#277 Updated script for Change Phone Number scenario
  deploy/scripts/src/accounts/test.ts
Labels: k6

#284 [QA-309]: Updated load profile for Change Phone scenario
  deploy/scripts/src/accounts/test.ts
Labels: k6

#286 [QA-312]: Add stress profile for SPOT
  deploy/scripts/src/spot/test.ts
Labels: k6

#285 [QA-254] Unit tests for JavaScript library functions
  deploy/scripts/src/common/unit-tests.ts
Labels: javascript, k6

#287 [QA-311] Resolve URLs using `URL` when discovering static resources
  deploy/scripts/src/common/unit-tests.ts
  deploy/scripts/src/common/utils/request/static.ts
Labels: k6

#290 [QA-310] Allow Control Tower roles to assume execution role
  deploy/template.yaml
Labels: cloudformation

#292 [QA-313] Fix SQS call incorrect Promise types
  deploy/scripts/src/btm/test.ts
  deploy/scripts/src/common/utils/jslib/aws-sqs.d.ts
  deploy/scripts/src/cri-kiwi/ipvr.ts
  deploy/scripts/src/spot/test.ts
  deploy/scripts/src/txma/test.ts
Labels: documentation, javascript, k6

#293 [QA-315] Add IPVR SQS permissions
  deploy/template.yaml
Labels: cloudformation

#294 [QA-310] Fix Control Tower Role ARNs
  deploy/template.yaml
Labels: cloudformation

#295 [QA-315] Fix IPVR SQS ARN permissions
  deploy/template.yaml
Labels: cloudformation
