Repository govuk-one-login/performance-testing, pull requests merged in 2023-06, with the labels that each got.

#113 [QA-142]: Update OTEL config
  deploy/otel-config-template.yaml
Labels: opentelemetry

#120 [QA-142] Reduced push intervals of StatsD and OTEL to 10ms
  deploy/Dockerfile
Labels: docker, opentelemetry

#122 [QA-142]: Increasing StatsD buffer size and push intervals
  deploy/Dockerfile
Labels: docker, opentelemetry, k6

#123 [QA-41]: Updated workload model for Account Management scenarios
  deploy/scripts/src/accounts/test.ts
Labels: k6

#116 [QA-204] Rename environment variables
  .github/CODEOWNERS
  deploy/scripts/.eslintrc.json
  deploy/scripts/src/accounts/test.ts
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/cri-kiwi/test.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/test.ts
  deploy/scripts/src/ipv-core/test.ts
  deploy/scripts/src/mobile/test.ts
  deploy/scripts/src/mobile/utils/README
  deploy/scripts/src/mobile/utils/functions-mobile-journey.ts
  deploy/scripts/src/mobile/utils/url.d.ts
  deploy/scripts/src/mobile/utils/url.js
  deploy/template.yaml
Labels: k6

#129 [QA-215] Change default testing URL
  deploy/scripts/src/common/test.ts
Labels: k6

#130 [QA-142] Network interface debug
  deploy/template.yaml
Labels: opentelemetry

#133 [QA-193] Updated the CIC journey
  deploy/scripts/src/cri-kiwi/test.ts
  deploy/template.yaml
Labels: k6

#134 [QA-216]: Updated KBV script
  deploy/scripts/src/cri-orange/test.ts
  deploy/template.yaml
Labels: k6

#143 [QA-224] Feature branch testing workflow
  .github/workflows/feature-branch-publish.yaml
Labels: github_actions

#145 [QA-234] Bump node from 16-alpine3.16 to 16-alpine3.18 in deploy/
  deploy/Dockerfile
Labels: dependencies, docker

#148 [QA-235] Updated the happy path for Driving Licence
  deploy/scripts/src/cri-lime/data/drivingLicenceDVAData.csv
  deploy/scripts/src/cri-lime/data/drivingLicenceDVLAData.csv
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#150 [QA-237] Update k6 Docker repo
  deploy/Dockerfile
Labels: dependencies, docker, k6

#147 DCMAW-5593: Create performance test script for FE E2E Journey
  deploy/scripts/.eslintrc.json
  deploy/scripts/src/mobile/README.md
  deploy/scripts/src/mobile/authorize.test.ts
  deploy/scripts/src/mobile/frontend-e2e.test.ts
  deploy/scripts/src/mobile/test.ts
  deploy/scripts/src/mobile/utils/functions-mobile-journey.ts
  deploy/scripts/src/mobile/utils/k6/k6-utils.d.ts
  deploy/scripts/src/mobile/utils/k6/k6-utils.js
  deploy/scripts/src/mobile/utils/k6/url.d.ts
  deploy/scripts/src/mobile/utils/k6/url.js
  deploy/template.yaml
Labels: k6

#159 DCMAW-5594: Add BE e2e test script
  deploy/scripts/src/mobile/README.md
  deploy/scripts/src/mobile/authorize.test.ts
  deploy/scripts/src/mobile/backend-e2e.test.ts
  deploy/scripts/src/mobile/frontend-e2e.test.ts
  deploy/scripts/src/mobile/testSteps/backend.ts
  deploy/scripts/src/mobile/testSteps/frontend.ts
  deploy/scripts/src/mobile/utils/assertions.ts
  deploy/scripts/src/mobile/utils/config.ts
  deploy/scripts/src/mobile/utils/functions-mobile-journey.ts
  deploy/scripts/src/mobile/utils/test-client.ts
  deploy/scripts/src/mobile/utils/url.ts
Labels: k6

#163 [QA-240] Fix typo in SCENARIO flag documentation
  deploy/scripts/README.md
Labels: documentation

#164 DCMAW-5611: Smoke test journeys in Build
  deploy/scripts/src/mobile/utils/test-client.ts
Labels: k6

#162 [QA-209] Add scripts for BTM and TxMA
  deploy/scripts/src/btm/test.ts
  deploy/scripts/src/common/utils/aws/sqs.d.ts
  deploy/scripts/src/common/utils/aws/sqs.js
  deploy/scripts/src/common/utils/k6/k6-utils.d.ts
  deploy/scripts/src/common/utils/k6/k6-utils.js
  deploy/scripts/src/txma/test.ts
  deploy/template.yaml
Labels: k6

#167 [QA-244]: Updated IPV Core script
  deploy/scripts/src/ipv-core/data/stubUser.json
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#169 [QA-142] Add sleep time to post-build
  deploy/template.yaml
Labels: opentelemetry, cloudformation
