Repository govuk-one-login/performance-testing, pull requests merged in 2023-07, with the labels that each got.

#124 [QA-142] Replace Statsd with Dynatrace Output Extension
  deploy/Dockerfile
  deploy/otel-config-template.yaml
  deploy/template.yaml
Labels: docker, opentelemetry, k6

#168 [QA-246] Tidy JavaScript Library Files
  deploy/scripts/.eslintrc.json
  deploy/scripts/src/btm/test.ts
  deploy/scripts/src/common/utils/jslib/aws-sqs.d.ts
  deploy/scripts/src/common/utils/jslib/aws-sqs.js
  deploy/scripts/src/common/utils/jslib/index.d.ts
  deploy/scripts/src/common/utils/jslib/index.js
  deploy/scripts/src/common/utils/jslib/url.d.ts
  deploy/scripts/src/common/utils/jslib/url.js
  deploy/scripts/src/common/utils/k6/k6-utils.js
  deploy/scripts/src/mobile/testSteps/backend.ts
  deploy/scripts/src/mobile/utils/assertions.ts
  deploy/scripts/src/mobile/utils/k6/k6-utils.d.ts
  deploy/scripts/src/mobile/utils/url.ts
  deploy/scripts/src/txma/test.ts
Labels: javascript, k6

#176 [QA-248] CODEOWNERS for BTM and TxMA folders
  .github/CODEOWNERS
Labels: documentation

#177 [QA-249] Updated CIC happy path script
  deploy/scripts/src/cri-kiwi/test.ts
Labels: k6

#178 [QA-250] Added 2 BE requests for CIC
  deploy/scripts/src/cri-kiwi/test.ts
Labels: k6

#181 [QA-252]: Minor CRI Lime Test Script Enhancements
  deploy/scripts/src/cri-lime/test.ts
  deploy/template.yaml
Labels: k6, cloudformation

#183 [QA-255]: Update the approach for using environment names
  deploy/scripts/README.md
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/address/test.ts
  deploy/scripts/src/cri-orange/kbv/test.ts
  deploy/scripts/src/cri-orange/utils/config.ts
  deploy/template.yaml
Labels: documentation, k6, cloudformation

#182 [QA-236]: Updated Passport script
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#185 [QA-256] Accept new terms when signing-in in Authentication script
  deploy/scripts/src/authentication/test.ts
Labels: k6

#191 [QA-17] Updated load profile for Authentication scenarios
  deploy/scripts/src/authentication/test.ts
Labels: k6

#192 [QA-217]: Updated Orange CRI scripts for performance tests
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/data/addressCRIData.csv
  deploy/scripts/src/cri-orange/kbv.ts
Labels: k6

#180 [QA-245] Add SPoT permissions to CodeBuild policy
  deploy/template.yaml
Labels: cloudformation

#194 [QA-257] Updated F2F script
  deploy/scripts/src/cri-kiwi/test.ts
Labels: k6

#195 [QA-259]: Updated Lime CRI script
  deploy/scripts/src/cri-lime/data/passportData.csv
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#174 [QA-117]: Adding SPOT perf test scripts
  .github/CODEOWNERS
  deploy/scripts/src/spot/requestGenerator/spotReqFormat.ts
  deploy/scripts/src/spot/requestGenerator/spotReqGen.ts
  deploy/scripts/src/spot/test.ts
  deploy/template.yaml
Labels: k6, cloudformation

#198 [QA-263]: Updated IPV score script
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#197 [QA-205] Test Script for ID Reuse
  deploy/scripts/src/accounts/id-reuse.ts
  deploy/template.yaml
Labels: k6

#200 [QA-264] Updated ID Reuse authentication headers
  deploy/scripts/src/accounts/id-reuse.ts
Labels: k6

#202 [QA-266] Added a space between colon and quotation mark in template.yaml
  deploy/template.yaml
Labels: cloudformation

#211 [QA-251] Document Feature Branch Publish Action
  deploy/README.md
  docs/feature-branch-publish-action.png
Labels: documentation

#212 [QA-270] Update PR Checks to Include Merge Queues
  .github/workflows/pre-merge-checks.yml
Labels: github_actions

#214 DCMAW-6068: added tags for BE requests
  deploy/scripts/src/mobile/testSteps/backend.ts
Labels: k6

#217 DCMAW-6068: Mobile - add custom duration Trend for FE E2E script
  deploy/scripts/src/mobile/testSteps/backend.ts
  deploy/scripts/src/mobile/testSteps/frontend.ts
Labels: k6

#221 [QA-279]: IPV core script update
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#219 DCMAW-6068: Mobile - added duration trend metric to BE requests
  deploy/scripts/src/mobile/testSteps/backend.ts
Labels: k6

#226 [QA-276] Update k6 summary trend percentiles
  deploy/Dockerfile
Labels: docker

#227 [QA-275] Specify unit for 'duration' custom metric
  deploy/scripts/src/accounts/id-reuse.ts
  deploy/scripts/src/accounts/test.ts
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/cri-kiwi/test.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/kbv.ts
  deploy/scripts/src/ipv-core/test.ts
  deploy/scripts/src/mobile/testSteps/backend.ts
  deploy/scripts/src/mobile/testSteps/frontend.ts
Labels: opentelemetry, k6

#218 [QA-277] Retrieve static resources in IPV Core Script
  deploy/scripts/src/common/unit-tests.ts
  deploy/scripts/src/common/utils/request/static.ts
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#231 [QA-278] Update Build ID Metric Tag
  deploy/template.yaml
Labels: opentelemetry, cloudformation

#232 [QA-281] Add TxMA SQS Permissions
  deploy/template.yaml
Labels: cloudformation

#234 [QA-281] Add TxMA KMS Permissions
  deploy/template.yaml
Labels: cloudformation

#235 [QA-273] : Subject ID parameterization for ID reuse scripts
  deploy/scripts/src/accounts/data/summariseSubjectID.csv
  deploy/scripts/src/accounts/id-reuse.ts
Labels: k6

#236 [QA-213] Add Slack notifications to build commands
  deploy/Dockerfile
  deploy/reporting/slack.sh
  deploy/template.yaml
Labels: docker, cloudformation

#237 [QA-213] Fix Slack script path
  deploy/template.yaml
Labels: cloudformation
