Repository govuk-one-login/performance-testing, pull requests merged in 2023-09, with the labels that each got.

#307 [QA-211] Update npm package dependencies
  deploy/scripts/package-lock.json
Labels: dependencies

#275 [QA-267] Update BTM and TxMA test scripts
  deploy/scripts/src/btm/test.ts
  deploy/template.yaml
Labels: k6

#308 [QA-319]: Updated IPVR scenario to generate single user ID for all 3 event types
  deploy/scripts/src/cri-kiwi/ipvr.ts
  deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqGen.ts
Labels: k6

#313 [QA-320] Updated scripts to use timeRequest function
  deploy/scripts/src/accounts/id-reuse.ts
  deploy/scripts/src/accounts/test.ts
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/kbv.ts
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#325 [QA-335] IPV Core - Reduce think time and increase max VUs
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#329 [QA-337] : Updated test data approach in IPV core
  deploy/scripts/src/ipv-core/data/drivingLicence.json
  deploy/scripts/src/ipv-core/data/drivingLicenceData.ts
  deploy/scripts/src/ipv-core/data/passport.json
  deploy/scripts/src/ipv-core/data/passportData.ts
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#331 [QA-338] : Updated IPVR scripts for smoke tests
  deploy/scripts/src/cri-kiwi/ipvr.ts
  deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqFormat.ts
  deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqGen.ts
Labels: k6

#330 [QA-258] Add utilities for common assertions
  deploy/scripts/src/accounts/id-reuse.ts
  deploy/scripts/src/accounts/test.ts
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/common/unit-tests.ts
  deploy/scripts/src/common/utils/checks/assertions.ts
  deploy/scripts/src/common/utils/sleep/sleepBetween.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/kbv.ts
  deploy/scripts/src/cri-orange/utils/assertions.ts
  deploy/scripts/src/examples/dev-platform.ts
  deploy/scripts/src/ipv-core/test.ts
  deploy/scripts/src/mobile/frontend-e2e.test.ts
  deploy/scripts/src/mobile/testSteps/backend.ts
  deploy/scripts/src/mobile/testSteps/frontend.ts
  deploy/scripts/src/mobile/utils/assertions.ts
Labels: documentation, k6

#338 [QA-337] : Updated IPV core scripts to optimise load injector memory utilisation
  deploy/scripts/src/ipv-core/test.ts
Labels: k6
