Repository govuk-one-login/performance-testing, pull requests merged in 2024-07, with the labels that each got.

#717 [QA-241] Add cache to docker build
  .github/workflows/pre-merge-checks.yml
Labels: github_actions

#731 [QA-531] Adding a stress test load profile for OTG
  deploy/scripts/src/cri-orange/otg.ts
Labels: k6

#743 [QA-537] Updating Auth load profile to 20% of NFR volume
  deploy/scripts/src/authentication/test.ts
Labels: k6

#744 [QA-538] Updating the Auth load20 profile to full
  deploy/scripts/src/authentication/test.ts
Labels: k6

#755 [QA-540] Remove redundant package dependency
  koa-stub/src/package-lock.json
  koa-stub/src/package.json
Labels: dependencies, javascript

#756 [QA-541]: Updated Auth sign in scenario
  deploy/scripts/src/authentication/test.ts
Labels: k6

#774 [QA-545]: Update IPV Core scripts scenario for dev environment validation
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#776 [QA-546]: Reduce steady state duration of the IPV core adhoc tests in dev
  deploy/scripts/src/ipv-core/test.ts
Labels: k6
