Repository govuk-one-login/performance-testing, pull requests merged in 2024-08, with the labels that each got.

#757 [QA-539] Updating the OLH scripts to include the new stubs page
  deploy/scripts/src/accounts/test.ts
Labels: k6

#787 [QA-551] SonarCloud Dockerfile security alert fixes
  deploy/Dockerfile
Labels: docker

#788 [FPAD-3128] Reduce number of calls to Cognito
  deploy/scripts/src/fraud/test.ts
Labels: k6, typescript

#796 [FPAD-3128] Cognito debugging
  deploy/scripts/src/fraud/test.ts
Labels: k6, typescript

#786 [QA-548] Add HMRC KBV script
  deploy/scripts/src/cri-lime/hmrc-kbv.ts
Labels: k6, typescript

#797 [QA-550] Add debug logging to OLH changeEmail
  deploy/scripts/src/accounts/test.ts
Labels: k6

#822 [QA-561] Removing the sign-out step in the OLH changeEmail scenario
  deploy/scripts/src/accounts/test.ts
Labels: k6
