Repository govuk-one-login/performance-testing, pull requests merged in 2024-09, with the labels that each got.

#828 [QA-564] Adding the logout step back into OLH scenarios.
  deploy/scripts/src/accounts/test.ts
Labels: k6

#829 [QA-566] Updating the changeEmail OLH load profile to 30 iterations per second
  deploy/scripts/src/accounts/test.ts
Labels: k6

#831 [QA-568] Combine consecutive Docker RUN commands
  deploy/Dockerfile
Labels: docker

#830 [QA-567] Fix koa-stub userinfo retry mechanism
  koa-stub/src/controllers/callback.controller.js
  koa-stub/src/tests/app.test.js
Labels: javascript

#839 Updating line 68 for the vc-storage script
  deploy/scripts/src/bravo/vc-storage.ts
Labels: k6

#840 [QA-571] Group Dependabot updates
  .github/dependabot.yml
Labels: dependencies

#832 [QA-569] Updating the OLH scenarios to use the 'userPerformanceTest' user.
  deploy/scripts/src/olh/test.ts
Labels: k6

#851 [QA-573]: Reduced the low volume target for Address CRI to 15
  deploy/scripts/src/cri-orange/address.ts
Labels: k6

#767 [QA-543] Add github npm package registry
  .github/workflows/pre-merge-checks.yml
  .github/workflows/typedoc-publish.yml
Labels: github_actions

#855 [QA-576]: IPV Core: Updated script based on latest changes in user journey
  deploy/scripts/src/ipv-core/test.ts
  deploy/template.yaml
Labels: k6

#863 [QA-577] Changing the Address CRI lowVolume profile to 5 j/s
  deploy/scripts/src/cri-orange/address.ts
Labels: k6

#856 [QA-542] Combine IPV Core Scenarios
  deploy/scripts/src/ipv-core/test.ts
Labels: k6, typescript
