Repository govuk-one-login/performance-testing, pull requests merged in 2024-04, with the labels that each got.

#544 [QA-458]: Update response time changes in remaining scripts
  deploy/scripts/src/accounts/test.ts
  deploy/scripts/src/accounts/vc-storage.ts
  deploy/scripts/src/ais/test.ts
  deploy/scripts/src/cimit/test.ts
  deploy/scripts/src/cri-kiwi/BAV.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/kbv.ts
  deploy/scripts/src/cri-orange/nino-check.ts
  deploy/scripts/src/ipv-core/test.ts
Labels: k6, typescript

#566 [QA-473]: Update OLH script to use pageContentCheck utility
  deploy/scripts/src/accounts/test.ts
Labels: k6

#567 [QA-474]: Update Kiwi scripts to use pageContentCheck utility
  deploy/scripts/src/cri-kiwi/BAV.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
Labels: k6

#568 [QA-475]: Split core stub and CRI call in Address scenario
  deploy/scripts/src/cri-orange/address.ts
Labels: k6

#581 QA-480 Fix SAM Deploy Workflow step
  .github/workflows/koa-stub-main.yaml
Labels: github_actions

#569 [QA-432]: Add instructions on how to use reporting utility
  deploy/reporting/create-summary.sh
Labels: documentation

#587 [QA-482] Address SonarCloud code smells
  deploy/Dockerfile
  deploy/scripts/src/accounts/test.ts
  deploy/scripts/src/accounts/vc-storage.ts
  deploy/scripts/src/ais/test.ts
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/cimit/test.ts
  deploy/scripts/src/common/unit-tests.ts
  deploy/scripts/src/common/utils/authentication/totp.ts
  deploy/scripts/src/common/utils/config/load-profiles.ts
  deploy/scripts/src/common/utils/request/timing.ts
  deploy/scripts/src/cri-kiwi/BAV.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqFormat.ts
  deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqGen.ts
  deploy/scripts/src/cri-kiwi/utils/authorization.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/kbv.ts
  deploy/scripts/src/cri-orange/nino-check.ts
  deploy/scripts/src/examples/dev-platform.ts
  deploy/scripts/src/ipv-core/test.ts
Labels: docker, k6, typescript

#594 [QA-484] Adding static assets in a http.batch() request to the Address CRI script
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/utils/config.ts
Labels: k6

#596 [QA-485] Remove empty object declarations in check set parameters for `timeGroup()` and `timeRequest()`
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/common/utils/request/timing.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/kbv.ts
  deploy/scripts/src/cri-orange/nino-check.ts
  deploy/scripts/src/ipv-core/test.ts
Labels: k6, typescript

#597 [QA-425] Pin `koa-stub` GitHub actions versions
  .github/workflows/koa-stub-main.yaml
  .github/workflows/koa-stub-pr.yaml
Labels: github_actions

#598 [QA-486] Use `setup-node` workflow to set node version
  .github/workflows/pre-merge-checks.yml
  .github/workflows/typedoc-publish.yml
Labels: github_actions

#599 [QA-487]: Corrected transaction name in sign-in scenario
  deploy/scripts/src/authentication/test.ts
Labels: k6

#604 [QA-490] Updating the Address CRI script with the res variable
  deploy/scripts/src/cri-orange/address.ts
Labels: k6

#607 IPV Core - Fixed script due to recent changes
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#618 [QA-494] Static Asset testing of Passport CRI
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#619 [QA-496] New Loadprofile for Static Asset Testing
  deploy/scripts/src/common/utils/config/load-profiles.ts
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#620 [QA-497] Fixing LoadProfile name in cri-lime/test.ts
  deploy/scripts/src/cri-lime/test.ts
Labels: k6
