Repository govuk-one-login/performance-testing, pull requests merged in 2024-05, with the labels that each got.

#622 [QA-498]: NiNO CRI script changes
  deploy/scripts/src/cri-orange/nino-check.ts
Labels: k6

#625 [QA-499] Adding static asset testing to the Auth SignUp Journey
  deploy/scripts/src/authentication/test.ts
  deploy/template.yaml
Labels: k6

#605 [QA-488]: Update TxMA scripts with additional scenarios
  deploy/scripts/src/txma/requestGenerator/txmaReqFormat.ts
  deploy/scripts/src/txma/requestGenerator/txmaReqGen.ts
  deploy/scripts/src/txma/test.ts
Labels: k6

#638 [QA-500] Link to ECS dashboard in Slack notifications
  deploy/reporting/slack.sh
  deploy/template.yaml
Labels: enhancement, cloudformation

#641 Auth - Update script to run Sign In script at target 1000
  deploy/scripts/src/authentication/test.ts
Labels: k6

#642 [QA-503] Reduce `full` load profile steady state duration to 15m
  deploy/scripts/src/common/utils/config/load-profiles.ts
Labels: k6

#644 [QA-500] Update ECS dashboard ID
  deploy/template.yaml
Labels: cloudformation

#643 [QA-504] Pre-commit evergreening and beautysh fix
  .github/workflows/pre-merge-checks.yml
  .pre-commit-config.yaml
Labels: dependencies, github_actions

#645 [QA 452] Removing duplicated steps in the authentication script
  deploy/scripts/src/authentication/test.ts
Labels: k6

#656 [QA-510]: Updated body for persist VC call
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6

#657 [QA-510]: Add other VCs in the persist VC call and modify payload
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6

#664 [QA-511]: Update VC script
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6

#665 [QA-511]: Remove page content check from update VC transaction
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6
