Repository govuk-one-login/performance-testing, pull requests merged in 2024-06, with the labels that each got.

#672 [QA-512] changing TxMA sendSingleEvent from AUTH_LOG_IN_SUCCESS to AUTH_AUTHOR…
  deploy/scripts/src/txma/requestGenerator/txmaReqFormat.ts
  deploy/scripts/src/txma/requestGenerator/txmaReqGen.ts
  deploy/scripts/src/txma/test.ts
Labels: k6

#673 [QA-513]: Update permissions for PerformanceTesterRole to allow AssumeRole
  deploy/template.yaml
Labels: cloudformation

#674 [QA-514] Updating TxMA sendSingleEventScenario
  deploy/scripts/src/txma/requestGenerator/txmaReqFormat.ts
  deploy/scripts/src/txma/requestGenerator/txmaReqGen.ts
  deploy/scripts/src/txma/test.ts
Labels: k6

#675 [QA-515]: Updated IPV core script based on the latest changes in the user journey
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#676 [QA-517]: Adhoc load profile added for passport scenario in IPV core
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#694 [QA-521] : Scenario for isolated orch stub test
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#696 [QA-522]: Updated token generation call for Summarise VC
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6

#697 [QA-523]: Update VC JWT tokens in persist and update VC scenarios
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6

#707 [PSREDEV-1157] Update publish action trigger
  .github/workflows/publish.yaml
Labels: github_actions

#708 [QA-524]: Add debug statement in persist VC script
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6

#712 [QA-524]: Add test data for summarise VC smoke test
  deploy/scripts/src/accounts/data/summariseSubjectID.csv
Labels: k6

#714 [QA-527]: Create fresh test data for Summarise VC test
  deploy/scripts/src/accounts/data/summariseSubjectID.csv
Labels: k6

#715 [QA-526] Creating the OTG Perf Test Script
  deploy/scripts/src/cri-orange/otg.ts
  deploy/template.yaml
Labels: k6

#713 [QA-241] Use local docker image for CI unit tests
  .github/workflows/pre-merge-checks.yml
Labels: github_actions, docker

#716 [QA-528} Correcting the environment variable name for OTG
  deploy/scripts/src/cri-orange/otg.ts
Labels: k6

#718 [QA-529} Adding pageContentCheck to OTG script
  deploy/scripts/src/cri-orange/otg.ts
Labels: k6
