Repository govuk-one-login/performance-testing, pull requests merged in 2024-02, with the labels that each got.

#478 [QA-415] Update pre-commit dependencies
  .pre-commit-config.yaml
Labels: dependencies, github_actions

#480 [QA-405] Start auth journey without stub RP
  deploy/scripts/src/authentication/test.ts
  deploy/template.yaml
Labels: javascript, k6, cloudformation

#486 [QA-418] Revert s3 Bucket ACL settings
  .pre-commit-config.yaml
  deploy/template.yaml
Labels: github_actions, cloudformation

#488 [QA-408]: Script updates for AIS smoke testing
  deploy/scripts/src/ais/data/retrieveInterventionUser.csv
  deploy/scripts/src/ais/requestGenerator/aisReqGen.ts
Labels: k6

#489 [QA-408]: Updated page content for validation in Retrieve IV
  deploy/scripts/src/ais/test.ts
Labels: k6

#479 [QA-412] Add BAU load profiles for Passport CRI
  deploy/scripts/src/cri-lime/test.ts
Labels: javascript, k6

#491 [QA-423] - Increasing SPOT stress test volume to 2000r/s
  deploy/scripts/src/spot/test.ts
Labels: k6

#492 [QA-425] Pin GHAs to specific SHAs
  .github/workflows/feature-branch-publish.yaml
  .github/workflows/pre-merge-checks.yml
  .github/workflows/publish.yaml
Labels: dependencies, github_actions

#495 [QA-424]: Split OIDC and Auth calls in Auth scenarios
  deploy/scripts/src/authentication/test.ts
Labels: k6

#499 [QA-427] Increasing Auth SignIn low volume test to 30r/s
  deploy/scripts/src/authentication/test.ts
Labels: k6

#501 [QA-431]: Updated script for change email scenario
  deploy/scripts/src/accounts/test.ts
Labels: k6

#500 [QA-426]: AIS - Added data creation script and other minor changes
  deploy/scripts/src/ais/data/retrieveInterventionUser.csv
  deploy/scripts/src/ais/requestGenerator/aisReqGen.ts
  deploy/scripts/src/ais/test.ts
Labels: k6

#490 [QA-375] BAV CRI script
  deploy/scripts/src/cri-kiwi/BAV.ts
  deploy/scripts/src/cri-kiwi/data/BAVdata.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/scripts/src/cri-kiwi/utils/authorization.ts
  deploy/template.yaml
Labels: k6, cloudformation

#505 [QA-433] Update all scenarios in OLH script with formSelector
  deploy/scripts/src/accounts/test.ts
Labels: k6

#506 [QA-434] Update low volume AIS retrieveIV scenario target volume to 1000r/s
  deploy/scripts/src/ais/test.ts
Labels: k6

#507 [QA-436]: Added data creation profiles for IPV core and Bravo scripts
  deploy/scripts/src/accounts/id-reuse.ts
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#510 [QA-439]: Fresh test data for IPV core ID reuse scenario
  deploy/scripts/src/ipv-core/data/idReuseTestData.csv
Labels: k6

#511 [QA-440]: Remove Retrieve VC step from Persist scenario
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6
