Repository govuk-one-login/performance-testing, pull requests merged in 2024-03, with the labels that each got.

#521 [QA-447] Removing RP-stub check in Auth sign-in journey
  deploy/scripts/src/authentication/test.ts
Labels: k6

#522 [QA-448] AIS - Add name tags to metrics
  deploy/scripts/src/ais/test.ts
Labels: k6

#529 [QA-449] TxMA - Updated load profiles to reflect new NFR value
  deploy/scripts/src/txma/test.ts
Labels: k6

#531 [QA-450] Handle environment variables with a utility function
  deploy/scripts/src/accounts/test.ts
  deploy/scripts/src/accounts/vc-storage.ts
  deploy/scripts/src/ais/test.ts
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/btm/test.ts
  deploy/scripts/src/cimit/test.ts
  deploy/scripts/src/common/unit-tests.ts
  deploy/scripts/src/common/utils/config/environment-variables.ts
  deploy/scripts/src/common/utils/jslib/aws-sqs.d.ts
  deploy/scripts/src/cri-kiwi/BAV.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/scripts/src/cri-kiwi/ipvr.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/kbv.ts
  deploy/scripts/src/cri-orange/nino-check.ts
  deploy/scripts/src/cri-orange/utils/config.ts
  deploy/scripts/src/examples/dev-platform.ts
  deploy/scripts/src/ipv-core/test.ts
  deploy/scripts/src/mobile/utils/config.ts
  deploy/scripts/src/spot/test.ts
  deploy/scripts/src/txma/test.ts
Labels: javascript, k6

#528 [QA-445] Record response time percentiles in end of test summary
  deploy/Dockerfile
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/common/unit-tests.ts
  deploy/scripts/src/common/utils/config/load-profiles.ts
  deploy/scripts/src/common/utils/config/thresholds.ts
  deploy/template.yaml
Labels: enhancement, docker, k6, cloudformation, typescript

#533 [QA-455] Demo node app testing
  deploy/scripts/src/examples/dev-platform.ts
  deploy/template.yaml
Labels: k6, cloudformation, typescript

#538 [QA-456]: VC Storage - Update VC payload in persist VC script
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6

#540 [QA-456]: Added a debug statement for data creation
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6

#541 [QA-456]: Remove debug statement in VC storage script
  deploy/scripts/src/accounts/vc-storage.ts
Labels: k6

#542 QA-457: Updated fresh test data for Summarise VC
  deploy/scripts/src/accounts/data/summariseSubjectID.csv
Labels: k6

#543 [QA-454] Utility function documentation
  .github/workflows/typedoc-publish.yml
  deploy/scripts/package-lock.json
  deploy/scripts/package.json
  deploy/scripts/src/common/utils/README.md
  deploy/scripts/src/common/utils/authentication/totp.ts
  deploy/scripts/src/common/utils/aws/types.d.ts
  deploy/scripts/src/common/utils/checks/assertions.ts
  deploy/scripts/src/common/utils/config/load-profiles.ts
  deploy/scripts/src/common/utils/custom_metric/counter.ts
  deploy/scripts/src/common/utils/jslib/aws-sqs.d.ts
  deploy/scripts/src/common/utils/request/static.ts
  deploy/scripts/src/common/utils/request/timing.ts
  deploy/scripts/src/common/utils/sleep/sleepBetween.ts
  deploy/scripts/src/cri-kiwi/BAV.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/scripts/src/cri-lime/test.ts
Labels: documentation, k6, typescript

#545 [QA-454] Fix TypeDoc documentation publishing
  .github/workflows/typedoc-publish.yml
  deploy/scripts/src/common/utils/README.md
Labels: documentation, github_actions

#532 [QA-451] Standardise load profile definitions
  deploy/scripts/src/accounts/test.ts
  deploy/scripts/src/accounts/vc-storage.ts
  deploy/scripts/src/ais/test.ts
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/btm/test.ts
  deploy/scripts/src/cimit/test.ts
  deploy/scripts/src/common/unit-tests.ts
  deploy/scripts/src/common/utils/config/load-profiles.ts
  deploy/scripts/src/cri-kiwi/BAV.ts
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
  deploy/scripts/src/cri-kiwi/ipvr.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/kbv.ts
  deploy/scripts/src/cri-orange/nino-check.ts
  deploy/scripts/src/examples/dev-platform.ts
  deploy/scripts/src/ipv-core/test.ts
  deploy/scripts/src/mobile/authorize.test.ts
  deploy/scripts/src/mobile/backend-e2e.test.ts
  deploy/scripts/src/mobile/frontend-e2e.test.ts
  deploy/scripts/src/spot/test.ts
  deploy/scripts/src/txma/test.ts
Labels: k6, typescript

#512 [QA-428]: Speed up reporting utility
  deploy/reporting/create-summary.sh
Labels: k6

#548 [QA-463]: Updated IPV core scripts based on latest changes in the journey
  deploy/scripts/src/ipv-core/data/passportData.ts
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#550 [QA-459] Reduce memory usage
  deploy/scripts/src/authentication/test.ts
  deploy/template.yaml
Labels: bug, k6, cloudformation, typescript
