Repository govuk-one-login/performance-testing, pull requests merged in 2025-04, with the labels that each got.

#1185 [QA-846] Adding the I3 peak load profile for TxMA ESP & Audit-Service
  deploy/scripts/src/txma/clientEnrichment.ts
Labels: k6

#766 [QA-543] JWT signing in SPOT script
  .github/workflows/pre-merge-checks.yml
  .github/workflows/typedoc-publish.yml
  deploy/scripts/package-lock.json
  deploy/scripts/package.json
  deploy/scripts/src/common/utils/authentication/jwt.ts
  deploy/scripts/src/spot/request/generator.ts
  deploy/scripts/src/spot/request/types.ts
  deploy/scripts/src/spot/requestGenerator/spotReqGen.ts
  deploy/scripts/src/spot/test.ts
Labels: dependencies, k6, typescript

#1184 Update Auth with PER006I3 peak profile
  deploy/scripts/src/authentication/test.ts
Labels: k6

#1188 [QA-848]: Remove data-vocab dependency to unblock deployment
  deploy/scripts/package-lock.json
  deploy/scripts/package.json
Labels: dependencies

#1190 [QA-850] Adding Iteration 3 peak profiles for IPV Core
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#1189 [QA-849]: Add data vocab dependency
  .github/workflows/publish.yaml
  deploy/scripts/package-lock.json
  deploy/scripts/package.json
Labels: dependencies, github_actions

#1195 [QA-859] Adding I3 peak load profiles to EVCS.
  deploy/scripts/src/bravo/vc-storage.ts
Labels: k6

#1205 [QA-849]: Add data vocab dependency in perf test
  .github/workflows/publish.yaml
  deploy/scripts/package-lock.json
  deploy/scripts/package.json
Labels: dependencies, github_actions

#1208 QA-866 - Peak load profile updates for Lime CRI
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#1207 QA-862 Updated AIS data with the latest for persist IV and Retrive IV
  deploy/scripts/src/ais/data/retrieveInterventionUser.csv
Labels: k6

#1193 [QA-855]: Updated F2F and CIC scripts to separate IPV stub calls and AUT calls
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
Labels: k6

#1216 [QA-826] Adding Iteration 2 load profiles to IPVR
  deploy/scripts/src/cri-kiwi/ipvr.ts
Labels: k6

#1214 [QA-876] Adding PEAK Load profile to BAV
  deploy/scripts/src/cri-kiwi/BAV.ts
Labels: k6

#1217 [QA-826 Adding wait time into the IPVR script.
  deploy/scripts/src/cri-kiwi/ipvr.ts
  deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqFormat.ts
  deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqGen.ts
Labels: k6

#1220 [QA-826] Updating the allEvents PERF006I2 timeunit.
  deploy/scripts/src/cri-kiwi/ipvr.ts
Labels: k6

#1219 [QA-886]: IPV core script update for M1C scenario
  deploy/scripts/src/ipv-core/data/m1CData.ts
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#1218 [QA-885]: Updated Fraud script to include M1C flag
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#1224 QA-908 : Lime(Fraud) load profile updates/correction with right Pre & Max vusers
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#1232 Add idReuse load profile for identityM1CPeakTest
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#1233 QA-917:Address(Orange CRI):Perf006-I3 Peak test load profile update
  deploy/scripts/src/cri-orange/address.ts
Labels: k6

#1235 [QA-933]: Add Address Manual Entry scenario
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/data/addressMEData.csv
Labels: k6

#1236 [QA-934]: Add SPOT environment variables in CF template
  deploy/template.yaml
Labels: k6, cloudformation

#1222 [QA-849]: Add data vocab package in perf test
  .github/workflows/publish.yaml
  deploy/Dockerfile
  deploy/scripts/package-lock.json
  deploy/scripts/package.json
Labels: dependencies, docker

#1237 [QA-849]: Update working directory in Docker build and push
  .github/workflows/publish.yaml
Labels: github_actions

#1238 [QA-938]: Revert SPOT PR changes
  .github/workflows/publish.yaml
  deploy/Dockerfile
  deploy/scripts/package-lock.json
  deploy/scripts/package.json
Labels: dependencies, github_actions, docker

#1239 [QA-937]: Added load profiles for iteration 3 spike tests
  deploy/scripts/src/authentication/test.ts
  deploy/scripts/src/common/utils/config/load-profiles.ts
Labels: k6

#1240 [QA-939] Adding CRI-Lime I3 Spike profiles
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#1241 [QA-941]: Update IPV core script with Iteration 3 spike test profiles
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#1212 [QA-781]: Combined Mobile Backend and Frontend user journeys
  deploy/scripts/src/mobile/fe-be-combine-e2e.test.ts
  deploy/scripts/src/mobile/testSteps/backend.ts
  deploy/scripts/src/mobile/utils/config.ts
  deploy/template.yaml
Labels: k6

#1243 [QA-937]: Fix sign up spike load profile
  deploy/scripts/src/common/utils/config/load-profiles.ts
Labels: k6

#1242 [QA-942] Add CRI-Orange KBV I3 spike profile
  deploy/scripts/src/cri-orange/kbv.ts
Labels: k6

#1246 [QA-948] Adding OLH iteration 3 spike profiles
  deploy/scripts/src/common/utils/config/load-profiles.ts
  deploy/scripts/src/olh/test.ts
Labels: k6

#1251 [QA-951] Perf006 I3 load profiles for HMRC-check and OTG
  deploy/scripts/src/cri-orange/nino-check.ts
  deploy/scripts/src/cri-orange/otg.ts
Labels: k6

#1253 [QA-849]: Add data vocab dependency in performance testing
  .github/workflows/publish.yaml
  deploy/Dockerfile
  deploy/scripts/package-lock.json
  deploy/scripts/package.json
Labels: dependencies, github_actions, docker

#1256 [QA-955]: PERF006-I3 Spike Test Profile for BAV(CRI KIWI)
  deploy/scripts/src/cri-kiwi/BAV.ts
Labels: k6

#1258 [QA-956] Adding CIC & F2F I3 Spike Test Load Profiles
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
Labels: k6

#1261 [QA-849]: Add data vocab dependency in performance testing
  .github/workflows/pre-merge-checks.yml
  .github/workflows/publish.yaml
  deploy/Dockerfile
  deploy/scripts/package-lock.json
  deploy/scripts/package.json
Labels: dependencies, github_actions, docker

#1263 [Qa-961] Adding Iteration 3 spike load profiles to TxMA ESP & Audit-service
  deploy/scripts/src/txma/clientEnrichment.ts
Labels: k6

#1264 QA-960 : Address CRI Iteration3 Spike Test - Load profile update
  deploy/scripts/src/cri-orange/address.ts
Labels: k6

#1265 [QA-962]: Add spike test profile for IPVR BE
  deploy/scripts/src/cri-kiwi/ipvr.ts
Labels: k6

#1266 [QA-963]: Remove 'BRP' path from F2F script
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
Labels: k6

#1269 QA-968: I3 Regression load profile update to Auth & Orch scripts
  deploy/scripts/src/authentication/test.ts
Labels: k6

#1272 [QA-972]: Adding regression Load profiles for Address and Fraud
  deploy/scripts/src/common/utils/config/load-profiles.ts
  deploy/scripts/src/cri-lime/test.ts
  deploy/scripts/src/cri-orange/address.ts
Labels: k6

#1273 [QA-849]: Update SPOT scripts to remove data-vocab dependency
  deploy/scripts/src/spot/request/generator.ts
  deploy/scripts/src/spot/request/types.ts
  deploy/scripts/src/spot/test.ts
Labels: k6

#1274 [QA-970] Updating the soak test volumes for Auth & Orch.
  deploy/scripts/src/authentication/test.ts
Labels: k6

#1276 [QA-973]: Update the test target for Mobile Combined journey to 12
  deploy/scripts/src/mobile/fe-be-combine-e2e.test.ts
Labels: k6

#1278 [QA-975] Authentication - Add StressTestProfile
  deploy/scripts/src/authentication/test.ts
Labels: k6

#1279 [QA-976]: AIS PERF006 I3 load profiles for Spike tests
  deploy/scripts/src/ais/data/retrieveInterventionUser.csv
  deploy/scripts/src/ais/test.ts
Labels: k6

#1271 [QA-971] Updating The TiCF Build SQS Queue name in CF Template
  deploy/template.yaml
Labels: cloudformation
