Repository govuk-one-login/performance-testing, pull requests merged in 2025-05, with the labels that each got.

#1280 [QA-978]: Update k6 version to build the output-statsd extension
  deploy/Dockerfile
Labels: docker

#1293 [QA-984]: Add Mobile backend env vars in CF template
  deploy/template.yaml
Labels: cloudformation

#1294 QA-988 : Add I4 Peak test Load profiles to Authentication script
  deploy/scripts/src/authentication/test.ts
Labels: k6

#1295 QA-989 Update Iter 4 IPVCore load prof
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#1299 [QA-1025]: Mobile Platform BE Peak load test profile for I4
  deploy/scripts/src/mobile/v2-mobile-backend-get-client-attestation.ts
Labels: k6

#1300 [QA-1028]: Add Perf006 Iteration 4 Peak Test Profiles for CRI Lime
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#1298 [QA-1026] Adding a 2000j/s load profiles for TxMA
  deploy/scripts/src/txma/clientEnrichment.ts
Labels: k6

#1301 [QA-1027] Adding OLH Iteration 4 peak load profiles.
  deploy/scripts/src/olh/test.ts
Labels: k6

#1302 [QA-1032]: mobile V2 STS PEAK load profile for I4
  deploy/scripts/src/mobile/v2-sts-get-service-access-token.ts
Labels: k6

#1303 QA-1031: Load Profile update for Lime DL & DLA I4 Peak tests
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#1312 [QA-1053]:Update the test target for Mobile Combined journey to 15 for I3 Peak Test.
  deploy/scripts/src/mobile/fe-be-combine-e2e.test.ts
Labels: k6

#1314 QA-1059: Load profile and Retrieve Intervention Test Data update for AIS I4 Peak test
  deploy/scripts/src/ais/data/retrieveInterventionUser.csv
  deploy/scripts/src/ais/test.ts
Labels: k6

#1315 [QA-1055]: Add Perf006 I4 PeakTestProfile for DCMAW -Mobile (FE+BE)
  deploy/scripts/src/mobile/fe-be-combine-e2e.test.ts
Labels: k6

#1316 [QA-1060]: Update I4 PeakTest SignUp and Sign In Load Profile to adjust the VU counts
  deploy/scripts/src/common/utils/config/load-profiles.ts
Labels: k6

#1320 [QA-1067]: Address CRI - Experian KBV I4 Peak load profile
  deploy/scripts/src/cri-orange/kbv.ts
Labels: k6

#1322 [QA-1070]: Add Load Profile for I4 PeakTest
  deploy/scripts/src/cri-kiwi/BAV.ts
Labels: k6

#1291 [QA-982]: Update CIMIT script to use JWT signing utility
  deploy/scripts/src/cimit/data/getCICData.csv
  deploy/scripts/src/cimit/data/getCICData.json
  deploy/scripts/src/cimit/request/generator.ts
  deploy/scripts/src/cimit/request/types.ts
  deploy/scripts/src/cimit/requestGenerator/cimitReqFormat.ts
  deploy/scripts/src/cimit/requestGenerator/cimitReqGen.ts
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1213 [QA-563] TiCF CRI Script
  deploy/scripts/src/common/requestGenerator/txmaReqFormat.ts
  deploy/scripts/src/common/requestGenerator/txmaReqGen.ts
  deploy/scripts/src/fraud/ticf.ts
  deploy/scripts/src/txma/clientEnrichment.ts
  deploy/scripts/src/txma/requestGenerator/txmaReqFormat.ts
  deploy/scripts/src/txma/requestGenerator/txmaReqGen.ts
  deploy/scripts/src/txma/test.ts
  deploy/template.yaml
Labels: k6, cloudformation

#1323 [QA-1073]: Fix TICF CRI script issue
  deploy/scripts/src/fraud/ticf.ts
Labels: k6

#1324 [QA-1072]: Add CIMIT env vars in CF template
  deploy/template.yaml
Labels: k6

#1325 [QA-1074]: Fix CIMIT scripting issue
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1326 [QA-1075]: Update TICF CRI API calls
  deploy/scripts/src/common/utils/checks/assertions.ts
  deploy/scripts/src/fraud/ticf.ts
Labels: k6

#1327 [QA-1076]: CIMIT - Fix linting and other scripting issues
  deploy/scripts/src/cimit/request/generator.ts
  deploy/scripts/src/cimit/request/types.ts
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1328 QA-1077: Add I4 Peak test Load profile to CheckHMRC(ninoCheck)
  deploy/scripts/src/cri-orange/nino-check.ts
Labels: k6

#1329 [QA-1078]: Update request body for CIMIT POST requests
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1330 [QA-1079]:Add Load Profile for I4 PeakTest
  deploy/scripts/src/cri-kiwi/f2f-cic.ts
Labels: k6

#1331 [QA563A] TiCF TxMA Payload Fixes
  deploy/scripts/src/common/requestGenerator/txmaReqFormat.ts
  deploy/scripts/src/common/requestGenerator/txmaReqGen.ts
  deploy/scripts/src/fraud/ticf.ts
Labels: k6

#1333 QA-1063 IPVcore script - use Orch stub + devperf
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#1341 [QA-1085]: CIMIT - Update request body of Put Contra Indicator function
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1344 [QA-1087] - Updated CIMIT payload and scripts
  deploy/scripts/src/cimit/request/generator.ts
  deploy/scripts/src/cimit/request/types.ts
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1343 [QA-1084]: BAV - Adding Client assertion params in BAV script
  deploy/scripts/src/cri-kiwi/BAV.ts
  deploy/scripts/src/cri-kiwi/utils/authorization.ts
Labels: k6

#1347 [QA-563] Adding eventIDs to TiCF payloads
  deploy/scripts/src/common/requestGenerator/txmaReqFormat.ts
  deploy/scripts/src/common/requestGenerator/txmaReqGen.ts
  deploy/scripts/src/fraud/ticf.ts
Labels: k6

#1348 [QA-563] Adding eventIDs to all TxMA Payloads used in TiCF
  deploy/scripts/src/common/requestGenerator/txmaReqFormat.ts
  deploy/scripts/src/common/requestGenerator/txmaReqGen.ts
  deploy/scripts/src/fraud/ticf.ts
  deploy/scripts/src/txma/clientEnrichment.ts
  deploy/scripts/src/txma/test.ts
Labels: k6

#1255 [QA-954]: ID check async V2 script development
  deploy/scripts/src/mobile-id-check-async/test.ts
  deploy/scripts/src/mobile-id-check-async/testSteps/createSession.ts
  deploy/scripts/src/mobile-id-check-async/testSteps/getActiveSession.ts
  deploy/scripts/src/mobile-id-check-async/testSteps/getWellKnownJwks.ts
  deploy/scripts/src/mobile-id-check-async/testSteps/postAbortSession.ts
  deploy/scripts/src/mobile-id-check-async/testSteps/postBiometricToken.ts
  deploy/scripts/src/mobile-id-check-async/testSteps/postFinishBiometricSession.ts
  deploy/scripts/src/mobile-id-check-async/testSteps/postSetupVendorResponse.ts
  deploy/scripts/src/mobile-id-check-async/testSteps/postTxmaEvent.ts
  deploy/scripts/src/mobile-id-check-async/utils/apiSignatureV4Signer.ts
  deploy/scripts/src/mobile-id-check-async/utils/config.ts
  deploy/template.yaml
Labels: k6

#1350 [QA-1087]: CIMIT - Update the request body for post mitigations
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1353 [QA-1087]: CIMIT - Update mitigation approach
  deploy/scripts/src/cimit/request/generator.ts
  deploy/scripts/src/cimit/request/types.ts
  deploy/scripts/src/cimit/test.ts
  deploy/template.yaml
Labels: k6, cloudformation

#1354 QA-1090: migrate mobile BE async to use latest readid mock endpoint
  deploy/scripts/src/mobile-id-check-async/test.ts
  deploy/scripts/src/mobile-id-check-async/testSteps/postSetupBiometricSessionByScenario.ts
  deploy/scripts/src/mobile-id-check-async/testSteps/postSetupVendorResponse.ts
  deploy/scripts/src/mobile-id-check-async/utils/config.ts
  deploy/template.yaml
Labels: k6, cloudformation

#1355 [QA-1096]: CIMIT - Add I4 peak test profile
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1356 [QA-1096]: CIMIT - Correct the load test target
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1357 [QA-1100]: CIMIT - Move Get Contra Indicator call at the end
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1358 [QA-1107]: Account(Bravo)-VC Storage-Add Load Profile for I4 SpikeTest
  deploy/scripts/src/bravo/vc-storage.ts
Labels: k6

#1359 [QA-1106]: I4 Spike test Load profiles for LIME cri
  deploy/scripts/src/cri-lime/test.ts
Labels: k6

#1360 [QA-1109] TiCF Script changes
  deploy/scripts/src/fraud/ticf.ts
Labels: k6

#1361 [QA-1112]: Add I4 spike test target for CIMIT
  deploy/scripts/src/cimit/test.ts
Labels: k6

#1362 [QA-1118] Adding load profiles to the TiCF Script
  deploy/scripts/src/fraud/ticf.ts
Labels: k6

#1363 [QA-1120]: I4 Spike profile for (Orange CRI ) KBV
  deploy/scripts/src/cri-orange/kbv.ts
Labels: k6

#1364 [QA-1109] Adding a wait between payload generation in the TiCF script
  deploy/scripts/src/fraud/ticf.ts
Labels: k6

#1371 [QA-1109] changing the TxMA Event Date Formats for the TiCF Script.
  deploy/scripts/src/common/requestGenerator/txmaReqGen.ts
Labels: k6

#1373 [QA-1109] Editing TiCF wait times.
  deploy/scripts/src/fraud/ticf.ts
Labels: k6

#1375 QA-1125 : Orange I4 Spike Test profile update for Address & CheckHMRC
  deploy/scripts/src/cri-orange/address.ts
  deploy/scripts/src/cri-orange/nino-check.ts
Labels: k6

#1378 QA-1095: Auth - Update RP stub function to use the new URL
  deploy/scripts/src/authentication/test.ts
Labels: k6

#1380 [QA-1132]: IPV Core - Add Load Profile for I4 Soak and Stress Test
  deploy/scripts/src/ipv-core/test.ts
Labels: k6

#1379 [QA-1130] Creating dynamic eventID values for TxMA events in the TiCF script.
  deploy/scripts/src/common/requestGenerator/txmaReqGen.ts
  deploy/scripts/src/fraud/ticf.ts
  deploy/scripts/src/txma/clientEnrichment.ts
  deploy/scripts/src/txma/test.ts
Labels: k6

#1374 QA-1123: OLH Script changes for changeEmail, changePassword, changePhone & deleteAccount scenarios
  deploy/scripts/src/olh/test.ts
Labels: k6

#1383 [QA-1135]: Spike Test Profile for mobile ID Check async v2
  deploy/scripts/src/mobile-id-check-async/test.ts
Labels: k6

#1384 [QA-1136] Updating the identityProvingSuccess& signInSuccess in TiCF.
  deploy/scripts/src/fraud/ticf.ts
Labels: k6

#1382 [QA-1134]: I4 Authentication - Spike test profile
  deploy/scripts/src/authentication/test.ts
Labels: k6
